name: 🚀 Deploy website on push to Hosting

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: ['main']
    paths: ['out/**']
  push:
    branches: ['main']
    paths: ['out/**']

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /var/www/vh131491/data/www/starter.vladimirpolansky.com/
